### PR TITLE
Adding plist support

### PR DESCRIPTION
**Pull request by doowb**
Convert from plist to json, xml, or yaml.
Convert from json, xml, or yaml to plist format.

TODO:
- Add a couple of tests for xml and yaml.
- Add support for determining if a file with a .xml extension is a plist document.
- Allow writing plist document to .xml file.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
nice, thanks! developing themes/language definitions for sublime text was the reason I wanted this.

**Comment by jonschlinkert** [comment]
can the other TODO's be done after it's merged, or did you want to wait?

**Comment by doowb** [comment]
After the merge is fine. I just wanted to get those in there to remind me to do them or if someone else wants to, that's cool. The could be new feature requests.

**Comment by jonschlinkert** [comment]
:+1:

**Pull request merged**
