### PR TITLE
Pass `mergeAttrs: true` by default.

### PR DESCRIPTION
**Pull request by hariadi**
Merge attributes and child elements as properties of the parent, instead
of keying attributes off a child attribute object.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Nice job :+1:

**Comment by hariadi** [comment]
Forgot to include xml2js options. Did it parse your [gist](https://gist.github.com/jonschlinkert/8cdf94df5c7da4dc2e88) properly?

**Comment by jonschlinkert** [comment]
I didn't test, but the code looked right. I trust your work ;-)

**Comment by hariadi** [comment]
Haha :white_check_mark:

**Pull request merged**
