### PR TITLE
Documentation

### PR DESCRIPTION
**Pull request by hariadi**
Separate example

### CODE REVIEW

**Comment by jonschlinkert** [comment]
:+1:

**Comment by jonschlinkert** [comment]
@hariadi, do you like grunt-readme better than assemble-internal? Any suggestions for improvement?

**Comment by hariadi** [comment]
Yeah. grunt-readme is :metal:.

This is not suggestion but more of a question. How can sorting when using `{%= _.doc("examples-*.md") %}`. In this case want to render example-xml first, then examples-json.md and so on.

**Comment by jonschlinkert** [comment]
I guess we could add a compare function to the glob utils:

``` js
function compareFn(val) {
  val = val || function (a, b) {
    if (a.index >= b.index) {
      return 1;
    } else {
      return -1;
    }
  };
}

exports.globContent = function (src, compare_fn) {
  compare_fn = compareFn(compare_fn);
  var content = void 0;
  var index = 0;
  return content = grunt.file.expand(src).map(function (path) {
    index += 1;
    return {
      index: index,
      path: path,
      content: grunt.file.read(path)
    };
  }).sort(compare_fn).map(function (obj) {
    return obj.content;
  }).join(grunt.util.normalizelf(grunt.util.linefeed));
};
```

would that work?

**Comment by hariadi** [comment]
Not working (tested with adding manually to `utils.js`, and change `doc:` and `include:` to return `glob.globContent` - it is correct way?)

**Comment by jonschlinkert** [comment]
no that wasn't working code, I was just seeing if that is what you wanted

**Comment by hariadi** [comment]
Lol

**Pull request merged**
