### PR TITLE
Support YAML

### PR DESCRIPTION
**Pull request by hariadi**
Out of the box I'm using `xml2js` module for XML namespace `prefix:local` support. Working features:
- XML > JSON
- XML > YAML
- JSON > YAML
- YAML > JSON

JSON/YAML > XML not supported yet.

### CODE REVIEW

**Comment by jonschlinkert** [comment]
Wow! this is awesome! thank you for doing this. I really appreciate it!

**Comment by hariadi** [comment]
No problem.

In README still version 0.1.0. Bump it 1.2? :+1:

**Comment by jonschlinkert** [comment]
Sure, I added you as a maintainer on this project, so feel free to update the version if you wish :-)  

Thanks!

**Comment by jonschlinkert** [comment]
Btw, let me know if I added you properly, I haven't done that in a while

**Comment by hariadi** [comment]
Done. Update to 0.1.2

:shipit: to NPM!

**Comment by jonschlinkert** [comment]
:+1:  I'll do it now

**Pull request merged**
